---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: network-isolation-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.26.6
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
networking:
  disableDefaultCNI: true
