---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onboard-monitor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-only-role
rules:
- apiGroups: ["apps", ""] # "" indicates the core API group
  resources: ["deployments", "services"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-role
subjects:
- kind: ServiceAccount
  name: onboard-monitor
