---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: encryption-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
networking:
  disableDefaultCNI: true
